### PR TITLE
Spelling/Grammar mistakes

### PR DESCRIPTION
**Pull request by Maharramoff**
### Description of the changes:
- Grammar fixes
- Wording adjustments
- Wrong image path

### How changes were validated:
- Manual inspection

### CODE REVIEW

**Comment by GasimGasimzada** [comment]
Thank you for the fixes. Could you please clarify why you changed the path for the logo in about page?

EDIT: The URL that you have set up shows 404: https://frontend.az/static/images/appristas-h.png. When using GatsbyJS, the contents in the static directory are being accessed directly (no need to specific "static").

**Comment by Maharramoff** [comment]
> Could you please clarify why you changed the path for the logo in about page?

Clear. I thought the directory structure is the same. 
wrong-path

**Comment by Maharramoff** [comment]
According to the latest github feature you can request suggestion directly here: https://help.github.com/en/articles/incorporating-feedback-in-your-pull-request#applying-a-suggested-change

**Comment by GasimGasimzada** [comment]
README.az.md and README.md files are used for Github while /content/about.md is used for the website. For the Github one, the logo should be coming from the domain instead (or repo URL)

**Comment by GasimGasimzada** [comment]
Merged! Thank you!

**Pull request merged**
